//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation
import RxSwift

extension DomainResolver {

    func resolveDefaultGitHubSearchUseCase() -> DefaultGitHubSearchUseCase {
        let githubRepository = resolveGithubRepository()
        return DefaultGitHubSearchUseCase(dependency: .init(repository: githubRepository))
    }

    func resolveGithubRepository() -> GithubRepository {
        return provideGithubRepository()
    }

}

