//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation

extension DomainResolver {

    func resolveDomain() -> Domain {
        let domainModel = resolveDomainModel()
        return Domain(dependency: .init(model: domainModel))
    }

    func resolveDomainModel() -> DomainModel {
        return provideDomainModel()
    }

}

