//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Domain
import Foundation
import RxSwift

extension DataResolver {

    func resolveDefaultGithubRepository() -> DefaultGithubRepository {
        return DefaultGithubRepository(dependency: .init())
    }

}

