//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Domain
import Foundation
import RxSwift

extension DataResolver {

    func resolveDefaultGitHubRepository() -> DefaultGitHubRepository {
        return DefaultGitHubRepository(dependency: .init())
    }

}

