//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation
import UIKit

extension AppResolver {

    func resolveSampleModel() -> SampleModel {
        return provideSampleModel()
    }

    func resolveSampleViewController() -> SampleViewController {
        let sampleViewModel = resolveSampleViewModel()
        return SampleViewController(dependency: .init(viewModel: sampleViewModel))
    }

    func resolveSampleViewModel() -> SampleViewModel {
        let sampleModel = resolveSampleModel()
        return SampleViewModel(dependency: .init(model: sampleModel))
    }

}

